dist: xenial
sudo: required
addons:
  apt:
    update: true
    packages:
      - librsvg2-bin
      - parallel
cache:
  pip: true
stages:
  - test
  - name: deploy
    if: repo = faucetsdn/faucet AND tag IS present
env:
  global:
    - FAUCET_TEST_IMG=faucet/tests
    - MATRIX_SHARDS=6
script:
  - ./update_gmaster.sh
matrix:
  include:
jobs:
  include:
    - stage: test
      language: bash
